### ISSUE TITLE
.ipynb文件运行出问题，Pipeline.load()报错，请问CLI参数有什么作用，以及‘ab’代表什么？

### ISSUE THREAD

**Issue by fan123-zhang** [ashleychontos/pySYD#32]
![图片](https://user-images.githubusercontent.com/77425089/142749430-1aeb0e63-f95e-4152-98d9-34f2def6eae3.png)
![图片](https://user-images.githubusercontent.com/77425089/142749443-7e12b66c-5ca8-4e95-a665-a7c34b28511f.png)
![图片](https://user-images.githubusercontent.com/77425089/142749446-a407aed2-5c99-45b6-9d57-23b6c648e586.png)

**Comment by fan123-zhang** [comment]
是不是我的python版本的问题？

**Comment by ashleychontos** [comment]
I am not sure I totally understand what you are asking but I will do my best to try to provide a helpful answer and/or solution.

The notebook that you are showing was not released with the actual python package release (on PyPI via 'pip install'). Anything else on this GitHub page is actively being developed and thus expected to produce such errors. In fact for this case, _**both**_ the `pySYD` mode "load" and 'ab' parametrization (for Harvey component fits) are not in effect yet. Therefore for the time being, I recommend using one of our stable software releases.

**_We will have a lot of this operational very soon -- so keep an eye out! I have been diligently working on making the software more compatible with python notebooks!_**
