### ISSUE TITLE
replace int(oversampling_factor) with round(oversampling_factor)

### ISSUE THREAD

**Issue by MaryumSayeed** [ashleychontos/pySYD#46]
------

### Description
The int() function around oversampling_factor causes oversampling_factor to be 0 if it's less than 1 crashing the code. Solution: replace int() with round().

### Computing

Please provide (by editing) the following information:

 - **OS:** macOS
 - **Version:**  5.9.4
 - **Implementation:** command line

### Attachments

**In order to reproduce the issue from our end, please provide *both* the light curve and power spectrum for the relevant target!**<br/>
Attach the required data files here and if applicable, any figures or screenshots to help explain your problem.

### Other
Add any other relevant information here (e.g., links to related issues or solutions)
See highlighted line in code: 
[https://github.com/ashleychontos/pySYD/blob/master/src/pysyd/target.py#L365-L371](https://github.com/ashleychontos/pySYD/blob/master/src/pysyd/target.py#L365-L371)
------

## Summary Checklist:

- How were you using `pySYD` when you experienced the issue? <ul><li>- [x] CLI</li><li>- [ ] API</li><li>- [ ] jupyter</li></ul>
- Did you provide all the relevant information and files so that we can reproduce the error? <ul><li>- [ ] Yes</li><li>- [x] No</li></ul>
- Did you check if the issue has already been reported? <ul><li>- [x] Yes <br/> &rightarrow; Was there a proposed workaround or solution? <ul><li>- [x] Yes</li><li>- [ ] No</li><li>- [ ] Idk</li></ul></li><li>- [ ] No </li></ul>
- Do you know if the issue is version specific? <ul><li>- [ ] Yes* </li><li>- [] No</li><li>- [x] Idk</li></ul>
- Have you identified a workaround or solution? <ul><li>- [x] Yes* </li><li>- [ ] No</li></ul>
- Will you be submitting a pull request associated with this issue? <ul><li>- [ ] Yes </li><li>- [x] No</li><li>- [ ] Idk</li></ul>

<br/>
* If you selected 'Yes' for any of these points, please expand on each of them in more detail below.<br/> Note: If you found any relevant threads, questions, solutions or are submitting a pull request, please remember to provide links for any/all as these are incredibly helpful for future users. 

------

**Comment by ashleychontos** [comment]
This is now fixed in pysyd v6.10.5
