### ISSUE TITLE
setup does not work?

### ISSUE THREAD

**Issue by dk1010101** [ashleychontos/pySYD#50]
------

### Description + Fix

I've just installed pySYD for the first time using pip (first just using pip then i cloned the repo and installed it locally) and when i run setup i get a number of 'The filename, directory name, or volume label syntax is incorrect.' errors. The directories are created but no files can be found in them after running the setup.

Looking at the code i see that the way curl is called is .. understandable.. but will not work on all environments. On line 1128 in utils.py you have

`subprocess.call(['curl %s > %s' % (infile, outfile)], shell=True)`

whereas

`subprocess.call(['curl', infile, '>', outfile], shell=True)`

would be better as it works on latest python and on both windows and linux. 
Making this change locally fixes the problem.

### Computing

 - **OS:** Windows 11 Pro v22H2 OS build 22621.1992
 - **Version:** latest from git and latest from pip
 - **Implementation:** Conda 3-2023-07-1 running python 3.11.4

### Other
I didn't want to do the whole pull/sub for one line but can do if you would prefer although it is probably easier for you to do the one line change assuming you agree with it.

------

## Summary Checklist:

- How were you using `pySYD` when you experienced the issue? <ul><li>- [x] CLI</li><li>- [ ] API</li><li>- [ ] jupyter</li></ul>
- Did you provide all the relevant information and files so that we can reproduce the error? <ul><li>- [x ] Yes</li><li>- [ ] No</li></ul>
- Did you check if the issue has already been reported? <ul><li>- [x] Yes <br/> &rightarrow; Was there a proposed workaround or solution? <ul><li>- [ ] Yes</li><li>- [x] No</li><li>- [ ] Idk</li></ul></li><li>- [ ] No </li></ul>
- Do you know if the issue is version specific? <ul><li>- [ ] Yes* </li><li>- [x] No</li><li>- [ ] Idk</li></ul>
- Have you identified a workaround or solution? <ul><li>- [x] Yes* </li><li>- [ ] No</li></ul>
- Will you be submitting a pull request associated with this issue? <ul><li>- [ ] Yes </li><li>- [ ] No</li><li>- [x] Idk</li></ul>

<br/>
* If you selected 'Yes' for any of these points, please expand on each of them in more detail below.<br/> Note: If you found any relevant threads, questions, solutions or are submitting a pull request, please remember to provide links for any/all as these are incredibly helpful for future users. 
<br/>

------

Details of the solution are in the main text

------

**Comment by ashleychontos** [comment]
I was going to mention that the software does not yet include compatibility for python 3.11 but if it's only the one line that's failing for you, I am happy to implement that. Thanks for the heads up!

**Comment by dk1010101** [comment]
That is all that i have seen so far. There could be something else lurking but all the examples execute (at a first glance) as described in the docs.

**Comment by ashleychontos** [comment]
@dk1010101 following up on this...

I tried to incorporate your one-line workaround and setup failed on my macOSx (see attached), so it seems like this too does not work best across all platforms. Similarly, it did not download any of the data. <img width="687" alt="Screen Shot 2023-07-28 at 5 27 00 PM" src="https://github.com/ashleychontos/pySYD/assets/13820495/d97f4f95-db98-4fbb-b592-17d06b5f5f45"> 
Expanding on this, the raw string format '%s' should be the same for all so I'm very curious as to why this is failing now. Not to mention that there are other pysyd users that have windows OS and have not had issues with setup so this must be localized to the most recent python version and/or your platform... or some combination therein. Having more information about the error (or better, a screenshot of the terminal output) would be helpful.

**Comment by ashleychontos** [comment]
one thought that seems the easiest to resolve: defining a `command` one line up i.e., outside of where the subprocess is called *should* do the trick?

**Comment by ashleychontos** [comment]
@dk1010101 at your earliest convenience, please upload a special test version of `pysyd==0.10a2` and let me know if this resolves the issue.

**Comment by ashleychontos** [comment]
I will close this issue @dk1010101 if I do not hear back within the week
